version: "3.5"

services:

    iotagent-lora:
        image: ioeari/iotagent-lora
        hostname: iotagent-lora
        entrypoint: bin/iotagent-lora docker/config-docker.js
        depends_on:
            - mongo
            - orion
        ports:
            - "4061:4061"
        networks:
            iotagent-lora:
              ipv4_address: 172.49.1.12
            front:
                aliases:
                    - iotagent-lora.docker
            mongo:
            orion:
        volumes:
            - ../config/config-lora-docker.js:/opt/iotagent-lora/docker/config-docker.js
        stdin_open: true
        tty: true
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname == 2019-manager
            restart_policy:
                condition: any

networks:

    iotagent-lora:
        driver: overlay
        ipam:
            config:
                - subnet: 172.49.0.0/16
    front:
        driver: overlay
        ipam:
            config:
                - subnet: 172.40.0.0/16
    mongo:
        driver: overlay
        ipam:
            config:
                - subnet: 172.47.0.0/16
    orion:
        driver: overlay
        ipam:
            config:
                - subnet: 172.41.0.0/16
