version: "3.5"

services:

    mongo:
        image: mongo:3.6
        #Commented by Chandra
        #ports:
        #    - 27017:27017
        #Added by Chandra
        expose:
              - 27017
        networks:
            - mongo
        volumes:
            - /opt/mongo-data:/data/db
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname == 2019-manager
            restart_policy:
                condition: any
        ulimits:
            memlock: -1

networks:

    mongo:
        driver: overlay
        ipam:
            config:
                - subnet: 172.47.0.0/16
