version: "3.5"

services: 

  zookeeper:
        image: bitnami/zookeeper:latest
        environment:
           - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            front:
                aliases:
                  - zookeeper.docker
            zookeeper:
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname == 2019
            restart_policy:
                condition: any      

  nifi:
        #image: apache/nifi:1.10.0
        image: profirator/nifi:1.9.2
        ports:
          - 8080:8080
          - 8082:8082
        networks:
            front:
                aliases:
                  - nifi.docker
            nifi:
        volumes:
          - /opt/nifi/logs:/opt/nifi/logs
          - /opt/nifi/conf:/opt/nifi/conf
          - /opt/nifi/flowfile_repository:/opt/nifi/flowfile_repository
          - /opt/nifi/database_repository:/opt/nifi/database_repository
          - /opt/nifi/content_repository:/opt/nifi/content_repository
          - /opt/nifi/provenance_repository:/opt/nifi/provenance_repository            
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname == 2019
            restart_policy:
                condition: any

networks:

    front:
        driver: overlay
        ipam:
            config:
                - subnet: 172.40.0.0/16    

    zookeeper:
        driver: overlay
        ipam:
            config:
                - subnet: 172.57.0.0/16              

    nifi:
        driver: overlay
        ipam:
            config:
                - subnet: 172.58.0.0/16

