version: "3.5"

services:

  zookeeper:
        image: bitnami/zookeeper:latest
        environment:
           - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            front:
                aliases:
                  - zookeeper.docker
            zookeeper:
        deploy:
            replicas: 1
            restart_policy:
                condition: any

  nifi:
        image: apache/nifi:1.10.0
        ports:
          - target: 8080
            published: 8080
            protocol: tcp
            mode: host  
        environment:
          - NIFI_WEB_HTTP_HOST=0.0.0.0
          - NIFI_WEB_HTTP_PORT=8080
          - NIFI_CLUSTER_IS_NODE=true
          - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
          - NIFI_ZK_CONNECT_STRING=zookeeper:2181
          - NIFI_ELECTION_MAX_WAIT=1 min
        networks:
            front:
                aliases:
                  - nifi.docker
            nifi:
        deploy:
            replicas: 1
            restart_policy:
                condition: any

networks:

    front:
        driver: overlay
        ipam:
            config:
                - subnet: 172.40.0.0/16    

    zookeeper:
        driver: overlay
        ipam:
            config:
                - subnet: 172.57.0.0/16        

    nifi:
        driver: overlay
        ipam:
            config:
                - subnet: 172.58.0.0/16

