version: "3.5"

services:

    orion:
        # Always use a stable version
        image: fiware/orion:2.0.0
        depends_on:
            - mongo
        healthcheck:
            test: ["CMD", "curl", "-f", "http://0.0.0.0:1026/version"]
            interval: 1m
            timeout: 10s
            retries: 3
        ports:
            - 1026:1026
        networks:
            front:
                aliases:
                    - orion.docker
            orion:
            mongo:
        command: -dbhost mongo -corsOrigin __ALL
        deploy:
            restart_policy:
                condition: any

networks:

    front:
        driver: overlay
        ipam:
            config:
                - subnet: 172.40.0.0/16

    orion:
        driver: overlay
        ipam:
            config:
                - subnet: 172.41.0.0/16

    mongo:
        driver: overlay
        ipam:
            config:
                - subnet: 172.47.0.0/16
