version: "3.5"

services:

    tokenservice:
        image: ficodes/token-service:0.2
        depends_on:
            - keyrock
        networks:
            - front
        environment:
            - ACCESS_TOKEN_URL=http://keyrock:3000/oauth2/token
            - TOKEN_SERVICE_CLIENT_ID=### REPLACE WITH CLIENT ID OF KEYROCK ###
            - TOKEN_SERVICE_CLIENT_SECRET=### REPLACE WITH CLIENT SECRET OF KEYROCK ###
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname == 2019-manager
            restart_policy:
                condition: any


networks:

    front:
        driver: overlay
        ipam:
            config:
                - subnet: 172.40.0.0/16
