version: "3.5"

services:

    umbrella_elasticsearch:
        image: elasticsearch:2.4
        volumes:
            - /opt/umbrella-elasticsearch:/usr/share/elasticsearch/data
        command: elasticsearch -Des.index.max_result_window=50000
        networks:
            umbrella:
                aliases:
                    - elasticsearch.docker
            front:
                aliases:
                    - elasticsearch.docker
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname == 2019-manager
            restart_policy:
                condition: any

    umbrella:
        #image: apinf/api-umbrella:0.15.0-apinf2.1
        #image: challagonda/smartmaasa
        image: profirator/api-umbrella:pre-0.15.3
        depends_on:
            - mongo
            - umbrella_elasticsearch
        ports:
            - 443:443
        networks:
            umbrella:
            front:
               aliases:
                  - accounts.2019.smartmaas.services
                  - context.2019.smartmaas.services
                  - sthdata.2019.smartmaas.services
                  - umbrella.2019.smartmaas.services
                  - market.2019.smartmaas.services
            mongo:
        environment:
            - MAXMIND_LICENSE_KEY=CInU1dFAYh8alsUD
        configs:
            - source: umbrella10
              target: /etc/api-umbrella/api-umbrella.yml
            - source: umbrella11
              target: /opt/api-umbrella/embedded/openresty/nginx/conf/nginx.conf
        secrets:
            - umbrella.crt
            - umbrella.key
        ulimits:
                memlock: -1
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname == 2019-manager
            restart_policy:
                condition: any


################################################################################
# Configs
################################################################################

configs:

    umbrella10:
        file: ../config/api-umbrella.yml
    umbrella11:
        file: ../config/api-umbrella-nginx.conf


################################################################################
# Secrets
################################################################################

secrets:

    umbrella.crt:
        name: umbrella.crt-v7
        file: /etc/letsencrypt/live/2019.smartmaas.services/fullchain.pem
    umbrella.key:
        name: umbrella.key-v7
        file: /etc/letsencrypt/live/2019.smartmaas.services/privkey.pem


networks:

    front:
        driver: overlay
        ipam:
            config:
                - subnet: 172.40.0.0/16

    umbrella:
        driver: overlay
        ipam:
            config:
                - subnet: 172.46.0.0/16

    mongo:
        driver: overlay
        ipam:
            config:
                - subnet: 172.47.0.0/16
