app_env: production

services:
  - router
  - web

override_public_http_port: 443
override_public_http_proto: https

hosts:
  - hostname: umbrella.2019.smartmaas.services
    default: true
    ssl_cert: /run/secrets/umbrella.crt
    ssl_cert_key: /run/secrets/umbrella.key
    http_strict_transport_security: true
  - hostname: context.2019.smartmaas.services
    ssl_cert: /run/secrets/umbrella.crt
    ssl_cert_key: /run/secrets/umbrella.key
    http_strict_transport_security: true
  - hostname: accounts.2019.smartmaas.services
    ssl_cert: /run/secrets/umbrella.crt
    ssl_cert_key: /run/secrets/umbrella.key
    http_strict_transport_security: true
  - hostname: apis.2019.smartmaas.services
    ssl_cert: /run/secrets/umbrella.crt
    ssl_cert_key: /run/secrets/umbrella.key
    http_strict_transport_security: true
  - hostname: market.2019.smartmaas.services
    ssl_cert: /run/secrets/umbrella.crt
    ssl_cert_key: /run/secrets/umbrella.key
    http_strict_transport_security: true
  - hostname: sthdata.2019.smartmaas.services
    ssl_cert: /run/secrets/umbrella.crt
    ssl_cert_key: /run/secrets/umbrella.key
    http_strict_transport_security: true
  - hostname: dashboards.2019.smartmaas.services
    ssl_cert: /run/secrets/umbrella.crt
    ssl_cert_key: /run/secrets/umbrella.key
    http_strict_transport_security: true
  - hostname: ngsiproxy.2019.smartmaas.services
    ssl_cert: /run/secrets/umbrella.crt
    ssl_cert_key: /run/secrets/umbrella.key
  - hostname: 2019.smartmaas.services
    ssl_cert: /run/secrets/umbrella.crt
    ssl_cert_key: /run/secrets/umbrella.key
    http_strict_transport_security: true


gatekeeper:
    api_key_methods:
        - fiware-oauth2
        - header
        - getParam
    api_key_cache: true
    default_idp:
        backend_name: fiware-oauth2
        host: https://accounts.2019.smartmaas.services


mongodb:
    url: "mongodb://mongo:27017/api_umbrella"


elasticsearch:
    api_version: 2
    hosts:
        - http://umbrella_elasticsearch:9200

router:
    web_app_host: "umbrella.2019.smartmaas.services"


web:
    mailer:
        smtp_settings:
            address: mail
            port: 587
            openssl_verify_mode: 'none'
            authentication: login
            user_name: noreply@umbrella.2019.smartmaas.services
            password: tamp.ere

nginx:
  proxy_connect_timeout: 120
  proxy_read_timeout: 300
  proxy_send_timeout: 120
